# Generated by Django 6.1.1 on 2026-09-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key_encrypted',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='legacy_api_key_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='legacy_api_key_prefix',
            field=models.CharField(blank=True, default=None, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
