# Generated by Django 6.1.1 on 2026-09-12 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('source_url', models.URLField(max_length=2048)),
                ('description', models.TextField(max_length=5000)),
                ('kind', models.CharField(choices=[('landing_page', 'Landing page'), ('pricing_page', 'Pricing page'), ('hero', 'Hero'), ('blog', 'Blog'), ('navigation', 'Navigation'), ('footer', 'Footer'), ('dashboard', 'Dashboard'), ('other', 'Other')], db_index=True, default='landing_page', max_length=30)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=60)),
                ('selector', models.CharField(blank=True, max_length=200)),
                ('viewport_width', models.PositiveIntegerField(default=1440)),
                ('screenshot', models.ImageField(blank=True, upload_to='designs/screenshots/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='designs/thumbnails/')),
                ('capture_status', models.CharField(choices=[('pending', 'Queued'), ('processing', 'Capturing'), ('ready', 'Ready'), ('failed', 'Needs attention')], db_index=True, default='pending', max_length=16)),
                ('capture_error', models.CharField(blank=True, max_length=200)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('embedding_error', models.CharField(blank=True, max_length=200)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='designs', to='catalogue.tag')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SavedDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='catalogue.design')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'design'), name='unique_saved_design')],
            },
        ),
    ]
