# Generated by Django 6.1.1 on 2026-09-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_markdown',
            field=models.TextField(blank=True),
        ),
    ]
