# Generated by Django 6.1.1 on 2026-09-18 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_design_design_markdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DesignRating',
            fields=[
                ('design_id', models.UUIDField(primary_key=True, serialize=False)),
                ('score', models.FloatField(default=1000)),
                ('comparisons', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TasteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField(default=0)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('rate_window', models.DateTimeField(blank=True, null=True)),
                ('rate_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArenaBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField(default=0)),
                ('design_a', models.UUIDField()),
                ('design_b', models.UUIDField()),
                ('winner', models.UUIDField()),
                ('global_counted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['user', 'generation'], name='arena_personal_history')],
                'constraints': [models.CheckConstraint(condition=models.Q(('design_a__lt', models.F('design_b'))), name='arena_ordered_pair'), models.CheckConstraint(condition=models.Q(('winner', models.F('design_a')), ('winner', models.F('design_b')), _connector='OR'), name='arena_winner_in_pair'), models.UniqueConstraint(fields=('user', 'generation', 'design_a', 'design_b'), name='arena_one_personal_pair'), models.UniqueConstraint(condition=models.Q(('global_counted', True)), fields=('user', 'design_a', 'design_b'), name='arena_one_global_pair')],
            },
        ),
    ]
