# Generated by Django 6.1.1 on 2026-09-19 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_arenastate_designrating_tasteprofile_arenaballot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_window', models.DateTimeField(blank=True, null=True)),
                ('rate_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='arenaballot',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.arenaguest'),
        ),
        migrations.AddConstraint(
            model_name='arenaballot',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', True), ('guest__isnull', True), _connector='OR'), name='arena_single_voter_type'),
        ),
        migrations.AddConstraint(
            model_name='arenaballot',
            constraint=models.UniqueConstraint(fields=('guest', 'design_a', 'design_b'), name='arena_one_guest_pair'),
        ),
    ]
