# Generated by Django 6.1.1 on 2026-09-29 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_arenaguest_arenaballot_guest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=2048, unique=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='design',
            name='kind',
            field=models.CharField(choices=[('landing_page', 'Landing page'), ('pricing_page', 'Pricing page'), ('hero', 'Hero'), ('cta', 'Call to action'), ('auth_form', 'Auth form'), ('blog', 'Blog'), ('navigation', 'Navigation'), ('footer', 'Footer'), ('dashboard', 'Dashboard'), ('other', 'Other')], db_index=True, default='landing_page', max_length=30),
        ),
        migrations.AddField(
            model_name='design',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='catalogue.site'),
        ),
    ]
