# Generated by Django 6.1.1 on 2026-09-29 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_site_alter_design_kind_design_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='UILibrary',
            fields=[
                ('design', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ui_library', serialize=False, to='catalogue.design')),
                ('website_url', models.URLField(blank=True, max_length=2048)),
                ('github_url', models.URLField(blank=True, max_length=2048)),
                ('frameworks', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, max_length=10000)),
                ('pricing', models.JSONField(blank=True, default=list)),
                ('pricing_url', models.URLField(blank=True, max_length=2048)),
                ('pricing_checked_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='design',
            name='kind',
            field=models.CharField(choices=[('ui_library', 'UI library'), ('landing_page', 'Landing page'), ('pricing_page', 'Pricing page'), ('hero', 'Hero'), ('cta', 'Call to action'), ('auth_form', 'Auth form'), ('blog', 'Blog'), ('navigation', 'Navigation'), ('footer', 'Footer'), ('dashboard', 'Dashboard'), ('other', 'Other')], db_index=True, default='landing_page', max_length=30),
        ),
    ]
