# Generated by Django 6.1.1 on 2026-09-30 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_uilibrary_alter_design_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('source_url', models.URLField(max_length=2048, unique=True)),
                ('website_url', models.URLField(blank=True, max_length=2048)),
                ('repository_url', models.URLField(blank=True, max_length=2048)),
                ('description', models.TextField(max_length=5000)),
                ('notes', models.TextField(blank=True, max_length=10000)),
                ('installation', models.TextField(blank=True, max_length=10000)),
                ('compatible_agents', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('license', models.CharField(blank=True, max_length=160)),
                ('checked_at', models.DateField(blank=True, null=True)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
