# Generated by Django 6.1.1 on 2026-09-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_aiskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiskill',
            name='github_stars',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiskill',
            name='github_stars_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiskill',
            name='skills_sh_installs',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiskill',
            name='skills_sh_installs_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiskill',
            name='skills_sh_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
