# Generated by Django 6.1.1 on 2026-09-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_aiskill_github_stars_aiskill_github_stars_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='motion_notes',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='design',
            name='video',
            field=models.FileField(blank=True, upload_to='designs/videos/'),
        ),
        migrations.AddField(
            model_name='design',
            name='video_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='video_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='video_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
